---
- name: Disable password-based SSH sessions
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  notify: restart ssh

- name: Remove the default pi user
  ansible.builtin.user:
    name: pi
    state: absent
    remove: yes
