---
- name: "Create or modify user groups | {{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    append: yes
    state: present
  when: (item.groups is defined) and (item.groups|length > 0)

- name: "Set passwordless sudo | {{ item.name }}"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/010_{{ item.name }}-nopasswd"
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    mode: '0440'
    validate: 'visudo -cf %s'
  when: item.sudo_nopass|d(False) == True

- name: "Add Public SSH keys | {{ item.name }}"
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_pub_key }}"
  when: item.ssh_pub_key is defined

- name: "Create or modify user password | {{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512', password_salt) }}"
    create_home: yes
    state: present