---
- name: "Update hostname | {{ new_hostname|d('(none)', true) }}"
  ansible.builtin.hostname:
    name: "{{ new_hostname }}"
  when: (new_hostname|length > 0) and (config.hostname != new_hostname)
# TODO reboot host?

- name: "Update timezone | {{ timezone|d('(none)', true) }}"
  command: "raspi-config nonint do_change_timezone {{ timezone }}"
  when: (timezone|length > 0) and (config.timezone != timezone)

- name: "Update locale | {{ locale|d('none', true) }}"
  command: "raspi-config nonint do_change_locale {{ locale }}"
  when: (locale|length > 0) and (config.locale != locale)

- name: "Update keyboard layout | {{ keyboard_layout|d('none', true) }}"
  command: "raspi-config nonint do_configure_keyboard {{ keyboard_layout }}"
  when: (keyboard_layout|length > 0) and (config.keyboard_layout != keyboard_layout)

# TODO un/install apt packages?
