---
- name: Install system packages
  ansible.builtin.apt:
    pkg: "{{ packages.install }}"
    state: present
    update_cache: yes
    cache_valid_time: 1800
  when: packages.install is defined and packages.install

- name: Enable systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop: "{{ packages.services }}"
  when: packages.services is defined and packages.services

- name: Remove system packages
  ansible.builtin.apt:
    pkg: "{{ packages.uninstall }}"
    state: absent
  when: packages.uninstall is defined and packages.uninstall

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip.install }}"
  when: pip.install
