---
all:
  children:

    # Brand new Raspberry Pi's looking to join the network
    # These are using default credentials from a fresh Raspberry Pi OS installation
    bootstrap_hosts:
      hosts:
        raspberrypi

    # Existing Raspberry Pi's that need to be managed
    configure_hosts:
      hosts:
        rfgateway

    # Other fresh OS installs
    bootstrap_openhabian:
      hosts:
        openhabian
