---
- name: Raspberry Pi Hosts
  hosts: raspberries
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  vars_files:
    - host_vars/vault.yml

  tasks:
    - name: Initial rpi configs
      tags: init
      block:
        - name: Gather rpi config
          config_txt_facts:
        - name: Update rpi config
          ansible.builtin.import_role:
            name: rpi_settings

    - name: Software installs
      tags: software
      block:
        - name: Common software
          ansible.builtin.import_role:
            name: common
        - name: Docker
          ansible.builtin.import_role:
            name: geerlingguy.docker

    - name: Gateway specific installs
      tags: gateway
      ansible.builtin.import_role:
        name: mysensors
      when: inventory_hostname == 'rfgateway'
