---
- name: Configure SPI
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  when: mysensors_data.add_spi
  block:
    - name: Check for SPI in config.txt
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        regexp: ^#dtparam=spi=on$
        line: dtparam=spi=on
      register: spi

    - name: Rebooting to enable SPI
      ansible.builtin.reboot:
      when: spi.changed

- name: Configure, compile and install the gateway code from mysensors.org
  ansible.builtin.import_tasks: mysgw.yml
  when: mysensors_data.options
