---
- name: Clone MySensors source
  ansible.builtin.git:
    clone: true
    update: true
    repo: https://github.com/mysensors/MySensors
    dest: MySensors
    version: development
    depth: 1
    single_branch: true
  register: gitclone

- name: Configure MySensors
  vars:
    mys_options: "{{ ' '.join(mysensors_data.options) }}"
  ansible.builtin.command: ./configure {{ mys_options }}
  args:
    chdir: MySensors

- name: Install MySensors
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  block:
    - name: Create MySensors binary
      ansible.builtin.command: make install
      args:
        chdir: MySensors
      ignore_errors: true # this command produces a lot of C++ warning noise

    - name: Enable MySensors service
      ansible.builtin.systemd:
        name: mysgw.service
        state: restarted
        enabled: true

    # the first run of the service will create a mysensors.conf file
    # so the modifications must happen after service start
    - name: Turn on logging
      ansible.builtin.lineinfile:
        path: /etc/mysensors.conf
        regexp: ^log_file=
        line: log_file=1
      register: logging1

    - name: Create log file path
      ansible.builtin.file:
        path: /var/log/mysgw/
        state: directory
        mode: u=rwx

    - name: Configure log file path
      ansible.builtin.lineinfile:
        path: /etc/mysensors.conf
        regexp: ^log_filepath=
        line: log_filepath=/var/log/mysgw/mysgw.log
      register: logging2

    - name: Restart MySensors service
      ansible.builtin.systemd:
        name: mysgw.service
        state: restarted
        enabled: true
        daemon_reload: true
      when: logging1.changed or logging2.changed
