---
- name: Configure SPI
  become: yes
  become_user: root
  become_method: sudo
  when: mysensors.add_spi
  block:
    - name: Check for SPI in config.txt
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        regexp: '^#dtparam=spi=on$'
        line: 'dtparam=spi=on'
      register: spi

    - name: Rebooting to enable SPI
      ansible.builtin.reboot:
      when: spi.changed

# configure, compile and install the gateway code from mysensors.org
- import_tasks: gateway.yml
  when: mysensors.options
