---
- name: "Configure Mosquitto"
  become: yes
  become_user: root
  become_method: sudo
  block:
    - name: "Stop mosquitto service"
      ansible.builtin.systemd:
        name: mosquitto
        state: stopped

    - name: "Copy password file"
      ansible.builtin.copy:
        src: "{{ mysensors.mosquitto.pw_src_file }}"
        dest: /etc/mosquitto/passwd

    - name: "Copy config file"
      ansible.builtin.copy:
        src: "{{ mysensors.mosquitto.conf_src_file }}"
        dest: /etc/mosquitto/conf.d/custom.conf

    - name: "Restart mosquitto service"
      ansible.builtin.systemd:
        name: mosquitto
        state: restarted
