---

- name: Read simple boolean options
  include_tasks:
    file: boolean_options.yml
  vars:
    parsed_value: "{{ 0 if item.value else 1 }}"
  loop: "{{ boolean_options | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: boolean_options
