---
- name: Install system packages
  ansible.builtin.apt:
    pkg: "{{ common_packages.install }}"
    state: present
    update_cache: true
    cache_valid_time: 1800
  when: common_packages.install is defined and common_packages.install

- name: Enable systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: "{{ common_packages.services }}"
  when: common_packages.services is defined and common_packages.services

- name: Remove system packages
  ansible.builtin.apt:
    pkg: "{{ common_packages.uninstall }}"
    state: absent
  when: common_packages.uninstall is defined and common_packages.uninstall

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ common_pip.install }}"
  when: common_pip.install
