---
# default connection info
# https://www.openhab.org/docs/installation/openhabian.html#passwords
ansible_host: openhabian.home
ansible_user: openhabian
ansible_password: openhabian
ansible_become_pass: openhabian

# set this to use the security tasks in ssh_connection_setup
add_to_known_hosts: True

users:
  # Update the password for the default users
  - name: pi
    password: "{{ pi_user_newpw }}"

  - name: openhabian
    password: "{{ pi_user_newpw }}"
    ssh_pub_key: "{{ user1_pubkey }}"
    sudo_nopass: True

# Remove password based logins and remove the default pi user
# Be careful with this setting as it could make your pi unusable if something is misconfigured
# extra_security: True

### MySensors ROLE vars ###
mysensors:
  # passed directly to /configure
  options:
    - "--my-debug=enable"
    - "--spi-driver=SPIDEV"
    - "--spi-spidev-device=/dev/spidev0.0"
    - "--my-transport=rfm69"
    - "--my-rfm69-frequency=915"
    - "--my-rfm69-irq-pin=15"
    - "--my-rfm69-cs-pin=26"
    - '--extra-cxxflags="-DMY_RFM69_RST_PIN=22"'
    - "--my-is-rfm69hw"
    - "--my-security-password={{ rfgateway_password }}"
    - "--my-rfm95-encryption-enabled"
    - "--my-gateway=mqtt"
    - "--my-controller-ip-address=127.0.0.1"
    - "--my-mqtt-publish-topic-prefix=mysensors-out"
    - "--my-mqtt-subscribe-topic-prefix=mysensors-in"
    - "--my-mqtt-client-id=mygateway1"
