---
# default connection info
# https://www.raspberrypi.org/documentation/linux/usage/users.md
ansible_host: raspberrypi.local
ansible_user: pi
ansible_password: raspberry

### SECURITY ROLE vars ###

# set this to use the security tasks in ssh_connection_setup
add_to_known_hosts: True

# alternative: just skip host checking
# ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

users:
  # Create a regular user like the pi user
  - name: toni
    password: "{{ user1_pw }}"
    groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,spi,i2c,gpio
    ssh_pub_key: "{{ user1_pubkey }}"

  # Update the password for the default pi user
  - name: pi
    password: "{{ pi_user_newpw }}"

# Remove password based logins and remove the default pi user
# Be careful with this setting as it could make your pi unusable if something is misconfigured
# extra_security: True

### LINUX_COMMON ROLE vars ###

packages:
  install:
    - python3-pip

pip:
  install:
    - RPI.GPIO

### RPI_SETTINGS ROLE vars ###

boolean_options:
  spi: True
  i2c: True
