---
ansible_host: rfgateway.home
ansible_user: toni
ansible_ssh_private_key_file: /Users/toni/.ssh/pi_id_rsa
ansible_become_pass: "{{ user1_pw }}"

boolean_options:
  spi: True
  i2c: True

packages:
  install:
    - python3-pip
    - git
    - mosquitto
    - mosquitto-clients
  services:
    - mosquitto

pip:
  install:
    - RPI.GPIO
    # - adafruit-blinka
    # - adafruit-circuitpython-ssd1306
    # - adafruit-circuitpython-framebuf
    # - adafruit-circuitpython-rfm69

### MySensors ROLE vars ###
mysensors:
  add_spi: False

  # configure mosquitto gateway auth
  # ex: mosquitto_passwd -c files/mosquitto_passwd <username>
  mosquitto:
    pw_src_file: "/playbook/files/mosquitto_passwd"
    conf_src_file: "/playbook/files/mosquitto.conf"

  # passed directly to /configure
  options:
    - "--my-debug=enable"
    - "--spi-driver=SPIDEV"
    - "--spi-spidev-device=/dev/spidev0.1"
    - "--my-transport=rfm69"
    - "--my-rfm69-frequency=915"
    - "--my-rfm69-irq-pin=15"
    - "--my-rfm69-cs-pin=26"
    - '--extra-cxxflags="-DMY_RFM69_RST_PIN=22"'
    - "--my-is-rfm69hw"
    - "--my-security-password={{ rfgateway_password }}"
    - "--my-rfm95-encryption-enabled"
    - "--my-gateway=mqtt"
    - "--my-controller-ip-address=127.0.0.1"
    - "--my-mqtt-publish-topic-prefix=mysensors-out"
    - "--my-mqtt-subscribe-topic-prefix=mysensors-in"
    - "--my-mqtt-client-id=mygateway1"
    - "--my-mqtt-user=automation"
    - "--my-mqtt-password={{ mosquitto_pw }}"
